language: ruby
rvm: 2.5.5
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake
deploy:
  provider: heroku
  app: backend-kfritsch
  api_key:
    secure: eXIi0mGfJZiv217/kJpAckT5JDIfMppx8UsFTpCGuf5hNAo1fGmmzacx7Kg9kCIpKOSP9d/rhn37VYllJZCn/HjkNrec4TGB3GPDSBr+k9DzIal2t9WXDjGWRnjycsRcSjJDkWbQTvq0IdcTOG0N63IOZS2FqoALpqBFeFTYl6wEok5XlfQxmPjdgo+N9pE8GKzfiWTikA1bPCfBbO5Yl4V8T8wyz1ZvrgYRWiM/M23QpjzD9GqPMlEU8zR7dY3vuEV1tqb8VlWXuwCUZGhWbXcuNyHQlpQJ6KxqXFLT6JkKRIiCTnlhyhAnwkImXf2YynQEhTZtrPGqD7DBUP+3jNb6/SwK8MWwG0/jdZJbbq0sjcKCfJnUiJ68Bwej13V/Y4UPEsQLCLeLESKKLjQgMJEzC+XgV6d9Qn8WS0qD39QRHvCJG6w71jiD/2Jd+9na+OGsEWtEuEzYYQ5WKEWZqST3CLrdIaNbCd8gve5sQqRIifLi0LETOgZfqw2E2JB9eWUxbxugkqAdN5D3gxyfvcli7lLON9N8RTj6cMJBx+j5XzzrnUbozgsNi81yWsOmSlH1lldrvA7jcgUFOYtI4Sf+6S4WrfL4EUl9Sae3q2/ifLo7Cd3TdLY1RLIMetzus2M4auktE3tWJYEsCcCNHRuEN/ucxJz84SUjWiL41HE=
